# # leishen
#platformName: Android
#platformVersion: 5.1.1
#deviceName: emulator-5554 (5.1.1)
##
# real device
platformName: Android
platformVersion: 4.4.2
deviceName: 10.10.6.203:30016


appName: OBSomatosensoryWorld_HNYD_V2.1.21.apk
appPackage: com.orbbec.gdgamecenter
appActivity: com.orbbec.gdgamecenter.activity.LaunchActivity

noReset: True
#unicodeKeyboard: True
#resetKeyboard: True
ip: 127.0.0.1
port: 4723